### ISSUE TITLE
Need template for Avery presta-94107

### ISSUE THREAD

**Issue by chandrakantsavant** [amattu2/avery-fpdf-labels#3]
Hello @amattu2 
Can you please provide the template for Avery presta-94107 with 2" x 2" (3 columns and 4 rows) on one page? I really need it.
Below is Avery's template URL
https://www.avery.com/templates/presta-94107

**Comment by amattu2** [comment]
It looks like this template is mainly for images, which is not supported. Are you using this template for text?

**Comment by chandrakantsavant** [comment]
Thank you @amattu2 for your prompt reply.
Actually, we are going to use this template for printing the QR code with some product info below the QR code

**Comment by amattu2** [comment]
> Thank you @amattu2 for your prompt reply. Actually, we are going to use this template for printing the QR code with some product info below the QR code

If possible, confirm the changes in PR #4 work with your requirements. If so, I'll merge and create a new release. If you want the box outlines on the PDF, pass true to the writeLabels function. 

e.g.

```PHP
// ...

$template->writeLabels(true);

// ...
```
